### ISSUE TITLE
[Feature Request] 1.20.3/4 Menu Support

### ISSUE THREAD

**Issue by R00tB33rMan** [comp500/BorderlessMining#90]
Menus from this plugin on 1.20.3/4 fail to load and immediately crash the game. Even though this may be the case, other components of the mod work just fine. Thank you for your contributions towards this project and I really appreciate it!

**Comment by pleepish** [comment]
will this mod be updated to 1.20.4 or not?

**Comment by DasBabyPixel** [comment]
Seems 1.20.4 has actually been implemented in #91. 
Would be nice if you could build and upload it to curse/modrinth @comp500, shouldn't take too much time. First of all it would allow less knowledgable people who can't build the mod themselves to actually build the mod, and it would allow for update automation through curseforge/modrinth APIs

**Comment by JessyCat92** [comment]
I build it my own but it still crashes ... I am just curious if this is an issue with 1.20.4 or an incompatibility with optifine as error says something with optifine ...

**Comment by JessyCat92** [comment]
To say it like this... I download current 1.20 Branch and run gradlew build - put 1.20.4 lib to fabric but going to graphic settings still causes this

`[06:23:02] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1352) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.7-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.optifine.gui.OptionFullscreenResolution failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.optifine.gui.GuiOtherSettingsOF.method_25426(GuiOtherSettingsOF.java:34) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1187) ~[client-intermediary.jar:?]
	at net.minecraft.class_446.actionPerformed(class_446.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_446.actionPerformed(class_446.java:160) ~[client-intermediary.jar:?]
	at net.optifine.gui.GuiScreenOF.method_25402(GuiScreenOF.java:92) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.optifine.gui.GuiOtherSettingsOF.method_25426(GuiOtherSettingsOF.java:34) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1187) ~[client-intermediary.jar:?]
	at net.minecraft.class_446.actionPerformed(class_446.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_446.actionPerformed(class_446.java:160) ~[client-intermediary.jar:?]
	at net.optifine.gui.GuiScreenOF.method_25402(GuiScreenOF.java:92) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Multi-argument modifier method modifyOption(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;)V in optifabric.compat.borderlessmining.new-mixins.json:OptionFullscreenResolutionNewMixin from mod optifabric failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap optifabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.optifine.gui.GuiOtherSettingsOF.method_25426(GuiOtherSettingsOF.java:34) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1187) ~[client-intermediary.jar:?]
	at net.minecraft.class_446.actionPerformed(class_446.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_446.actionPerformed(class_446.java:160) ~[client-intermediary.jar:?]
	at net.optifine.gui.GuiScreenOF.method_25402(GuiScreenOF.java:92) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 14 more`

**Comment by JessyCat92** [comment]
okay nevemind... got mym previous issue with the 1.20.4 verion with optifine solved by going with iris :D 

But I still don't have borderless window even if I use cutsom build from current 1.20 Branch...

**Comment by UltimatChamp** [comment]
Fixed in #97

**Comment by Nnnes** [comment]
Prebuilt JAR for 1.20.4 available from this fork: https://github.com/treymur/BorderlessMining

**Comment by Polda18** [comment]
This is the error that gets displayed in Launcher:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_4265.<init>(net.minecraft.class_310, int, int, int, int, int)'
```

This is the full error stack trace:
```
java.lang.NoSuchMethodError: 'void net.minecraft.class_4265.<init>(net.minecraft.class_310, int, int, int, int, int)'
	at link.infra.borderlessmining.config.ConfigScreen$ConfigListWidget.<init>(ConfigScreen.java:49)
	at link.infra.borderlessmining.config.ConfigScreen.method_25426(ConfigScreen.java:37)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1187)
	at com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$4(ModsScreen.java:193)
	at net.minecraft.class_4185.method_25306(class_4185.java:95)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:145)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:99)
	at net.minecraft.class_437.method_25412(class_437.java:414)
	at net.minecraft.class_312.method_1601(class_312.java:99)
	at net.minecraft.class_312.method_22686(class_312.java:180)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:180)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220)
	at net.minecraft.class_1041.method_15998(class_1041.java:287)
	at net.minecraft.class_310.method_1523(class_310.java:1349)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

And this is the full error log:
https://gist.github.com/Polda18/64f0d4fd8fb23cd608a4df0a62b1c5fd
